---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}
    
- name: pal-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/pal-tracker-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}    

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
 

- name: review-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: review

- name: production-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production 


jobs:
- name: build-and-deploy
  plan:
  - get: pal-tracker
    trigger: true
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: deploy
    params:
      manifest: pal-tracker/manifest.yml
      path: build-output/pal-tracker.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from Concourse"